/*************************************************
  HRCC, Copyright(C) Shanghai Haier Integrated Circuit Co., Ltd.
  Generated by HeadFileGenerator.exe
  File name:     HIC.h
  Version  :     1.0
  Rev  Date:     2013-02-27
*************************************************/

#ifndef _HIC_H
#define _HIC_H

	#include "hiint.h"

	#if defined (__HAIER_HR6P58L__)
		#include "HR6P58L.h"
	#endif

	#if defined (__HAIER_HR6P59HL__)
		#include "HR6P59HL.h"
	#endif

	#if defined (__HAIER_HR6P60HL__)
		#include "HR6P60HL.h"
	#endif

	#if defined (__HAIER_HR6P61L__)
		#include "HR6P61L.h"
	#endif

	#if defined (__HAIER_HR6P62HL__)
		#include "HR6P62HL.h"
	#endif

	#if defined (__HAIER_HR6P67L__)
		#include "HR6P67L.h"
	#endif

	#if defined (__HAIER_HR6P71__)
		#include "HR6P71.h"
	#endif

	#if defined (__HAIER_HR6P72L__)
		#include "HR6P72L.h"
	#endif

	#if defined (__HAIER_HR6P73BL__)
		#include "HR6P73BL.h"
	#endif

	#if defined (__HAIER_HR6P73HL__)
		#include "HR6P73HL.h"
	#endif

	#if defined (__HAIER_HR6P76L__)
		#include "HR6P76L.h"
	#endif

	#if defined (__HAIER_HR6P77L__)
		#include "HR6P77L.h"
	#endif

	#if defined (__HAIER_HR6P90__)
		#include "HR6P90.h"
	#endif

	#if defined (__HAIER_HR6P91__)
		#include "HR6P91.h"
	#endif

	#if defined (__HAIER_HR6P92__)
		#include "HR6P92.h"
	#endif

	#if defined (__HAIER_HR6P97__)
		#include "HR6P97.h"
	#endif

	#if defined (__HAIER_HR6P98__)
		#include "HR6P98.h"
	#endif

	#if defined (__HAIER_HR7P190FH__)
		#include "HR7P190FH.h"
	#endif

	#if defined (__HAIER_HR7P191FH__)
		#include "HR7P191FH.h"
	#endif

	#if defined (__HAIER_HR7P171__)
		#include "HR7P171.h"
	#endif

	#if defined (__HAIER_HR7P164__)
		#include "HR7P164.h"
	#endif

	#if defined (__HAIER_HR7P187__)
		#include "HR7P187.h"
	#endif

	#if defined (__HAIER_SSC1640__)
		#include "SSC1640.h"
	#endif

	#if defined (__HAIER_SSC1641__)
		#include "SSC1641.h"
	#endif

	#if defined (__HAIER_SSC1642__)
		#include "SSC1642.h"
	#endif

	#if defined (__HAIER_SSC1630__)
		#include "SSC1630.h"
	#endif

	#if defined (__HAIER_HR7P90H__)
		#include "HR7P90H.h"
	#endif

	#if defined (__HAIER_HR7P90HBL__)
		#include "HR7P90H.h"
	#endif

	#if defined (__HAIER_HR7P90HBLS__)
		#include "HR7P90H.h"
	#endif

	#if defined (__HAIER_HR7P91H__)
		#include "HR7P91H.h"
	#endif
	
	#if defined (__HAIER_HR7P91HBL__)
		#include "HR7P91H.h"
	#endif
	
	#if defined (__HAIER_HR7P91HBLS__)
		#include "HR7P91H.h"
	#endif

	#if defined (__HAIER_HR7P92H__)
		#include "HR7P92H.h"
	#endif
	
	#if defined (__HAIER_HR7P92HBL__)
		#include "HR7P92H.h"
	#endif
	
	#if defined (__HAIER_HR7P92HBLS__)
		#include "HR7P92H.h"
	#endif

	#if defined (__HAIER_HR7P193__)
		#include "HR7P193.h"
	#endif

	#if defined (__HAIER_HR7P194__)
		#include "HR7P194.h"
	#endif

	#if defined (__HAIER_HR7P194BL__)
		#include "HR7P194.h"
	#endif

	#if defined (__HAIER_HR7P194BLS__)
		#include "HR7P194.h"
	#endif
	
	#if defined (__HAIER_HR7P195F4__)
		#include "HR7P195.h"
	#endif

	#if defined (__HAIER_HR7P195F8__)
		#include "HR7P195.h"
	#endif
    
	#if defined (__HAIER_HR7P196__)
		#include "HR7P196.h"
	#endif
	
	#if defined (__HAIER_HR7P196BL__)
		#include "HR7P196.h"
	#endif

	#if defined (__HAIER_HR7P196BLS__)
		#include "HR7P196.h"
	#endif
	
	#if defined (__HAIER_HR6P90H__)
		#include "HR6P90H.h"
	#endif

	#if defined (__HAIER_HR6P91H__)
		#include "HR6P91H.h"
	#endif
	
	#if defined (__HAIER_HR6P92H__)
		#include "HR6P92H.h"
	#endif

	#if defined (__HAIER_HR7P190FI__)
		#include "HR7P190FI.h"
	#endif

	#if defined (__HAIER_HR7P191FI__)
		#include "HR7P191FI.h"
	#endif

	#if defined (__HAIER_HR7P90J__)
		#include "HR7P90J.h"
	#endif
	
	#if defined (__HAIER_HR7P90JBL__)
		#include "HR7P90J.h"
	#endif
	
	#if defined (__HAIER_HR7P90JBLS__)
		#include "HR7P90J.h"
	#endif

	#if defined (__HAIER_HR7P91J__)
		#include "HR7P91J.h"
	#endif
	
	#if defined (__HAIER_HR7P91JBL__)
		#include "HR7P91J.h"
	#endif
	
	#if defined (__HAIER_HR7P91JBLS__)
		#include "HR7P91J.h"
	#endif

	#if defined (__HAIER_HR7P92J__)
		#include "HR7P92J.h"
	#endif
	
	#if defined (__HAIER_HR7P92JBL__)
		#include "HR7P92J.h"
	#endif
	
	#if defined (__HAIER_HR7P92JBLS__)
		#include "HR7P92J.h"
	#endif
	
	#if defined (__HAIER_HR7P197H__)
		#include "HR7P197H.h"
	#endif
	
	#if defined (__HAIER_HR7P197HBL__)
		#include "HR7P197H.h"
	#endif
	
	#if defined (__HAIER_HR7P197HBLS__)
		#include "HR7P197H.h"
	#endif
	
	#if defined (__HAIER_HR7P197__)
		#include "HR7P197.h"
	#endif
	
	#if defined (__HAIER_HRT3080__)
		#include "HRT3080.h"
	#endif

	#if defined (__HAIER_P120__)
		#include "P120.h"
	#endif
	
	#if defined (__HAIER_P111__)
		#include "P111.h"
	#endif

	#if defined (__HAIER_HR7P166__)
		#include "HR7P166.h"
	#endif

	#if defined (__HAIER_HR7P159__)
		#include "HR7P159.h"
	#endif
	
	#if defined (__HAIER_HR7P155S__)
		#include "HR7P155.h"
	#endif

	#if defined (__HAIER_HR7P155M__)
		#include "HR7P155.h"
	#endif

	#if defined (__HAIER_HR7P155L__)
		#include "HR7P155.h"
	#endif

	#if defined (__HAIER_HR7P155SS__)
		#include "HR7P155S.h"
	#endif

	#if defined (__HAIER_HR7P155MS__)
		#include "HR7P155S.h"
	#endif

	#if defined (__HAIER_HR7P155LS__)
		#include "HR7P155S.h"
	#endif

	#if defined (__HAIER_HR7P160__)
		#include "HR7P160.h"
	#endif
	
	#if defined (__HAIER_HR7P167__)
		#include "HR7P167.h"
	#endif
	
	#if defined (__HAIER_HR7P192FLL1__)
		#include "HR7P192FLL1.h"
	#endif

	#if defined (__HAIER_HR7P196FLL__)
		#include "HR7P196FLL.h"
	#endif
	
	#if defined (__HAIER_HR7P196FLLBL__)
		#include "HR7P196FLL.h"
	#endif
	
	#if defined (__HAIER_HR7P196FLLBLS__)
		#include "HR7P196FLL.h"
	#endif
		
	#if defined (__HAIER_S200__)
		#include "S200.h"
	#endif
	
	#if defined (__HAIER_HS711__)
		#include "HS711.h"
	#endif
	
	#if defined (__HAIER_HR7P169__)
		#include "HR7P169.h"
	#endif

	#if defined (__HAIER_HR7P170__)
		#include "HR7P170.h"
	#endif
	
	#if defined (__HAIER_HR7P201__)
		#include "HR7P201.h"
	#endif
	
	#if defined (__HAIER_HR7P711T__)
		#include "HR7P711T.h"
	#endif
	
	#if defined (__HAIER_HR7P712__)
		#include "HR7P712.h"
	#endif
	
	#if defined (__HAIER_HR7P275__)
		#include "HR7P275.h"
	#endif
	
	#if defined (__HAIER_HR7P275BL__)
		#include "HR7P275.h"
	#endif
	
	#if defined (__HAIER_HR7P275BLS__)
		#include "HR7P275.h"
	#endif
	
	#if defined (__HAIER_HR7P276__)
		#include "HR7P276.h"
	#endif

	#if defined (__HAIER_HR7P293__)
		#include "HR7P293.h"
	#endif
	
	#if defined (__HAIER_HR7P152__)
		#include "HR7P152.h"
	#endif

	#if defined (__HAIER_HS7710__)
		#include "HS7710.h"
	#endif

	#if defined (__HAIER_S211__)
		#include "HS7710.h"
	#endif

	#if defined (__HAIER_HR7P159B__)
		#include "HR7P159B.h"
	#endif

	#if defined (__HAIER_HR7P155B__)
		#include "HR7P155B.h"
	#endif

	#if defined (__HAIER_HR7P156B__)
		#include "HR7P153.h"
	#endif

	#if defined (__HAIER_HR7P169B__)
		#include "HR7P169B.h"
		void ADC_channel14(void); 
	#endif

	#if defined (__HAIER_HR7P179__)
		#include "HR7P179.h"
		void ADC_channel14(void); 
	#endif
	
	#if defined (__HAIER_HR7P295__)
		#include "HR7P295.h"
	#endif
	
	#if defined (__HAIER_ES7P189__)
		#include "HS7710.h"
	#endif
	
	#if defined (__HAIER_ES7P1791__)
		#include "ES7P1791.h"
	#endif
	
	#if defined (__HAIER_ES7P1793__)
		#include "ES7P1793.h"
	#endif
	
	#if defined (__HAIER_WKJJ202__)
		#include "WKJJ202.h"
	#endif
	
	#if defined (__HAIER_ES7P2952__)
		#include "ES7P2952.h"
	#endif
	
	#if defined (__HAIER_ES7P2953__)
		#include "ES7P2953.h"
	#endif
	
	#if defined (__HAIER_ES7P2022__)
		#include "ES7P2022.h"
	#endif
	
	#if defined (__HAIER_ES7P2023__)
		#include "ES7P2023.h"
	#endif
	
	#if defined (__HAIER_ES7P173X__)
		#include "ES7P173X.h"
	#endif
	
	#if defined (__HAIER_HR7P179A__)
		#include "HR7P179A.h"
	#endif
	
	#if defined (__HAIER_ES7P203__)
		#include "ES7P203.h"
	#endif
	
	#if defined (__HAIER_ES7P1391__)
		#include "ES7P1391.h"
	#endif
	
	#include "stddef.h"
	
	#define PBit(adr, bit)        ((unsigned)(&adr)*8+(bit))

	#define Bit(x)                (1<<(x))

	#define BitSet(var, bitno)    ((var) |= (1 << (bitno)))

	#define BitClr(var, bitno)    ((var) &= ~(1 << (bitno)))

#endif

