/*************************************************
  HRCC, Copyright(C) Shanghai Haier Integrated Circuit Co., Ltd.
  Generated by HeadFileGenerator.exe
  File name:     HR7P153.h
  Version  :     1.0
  Rev  Date:     2016/3/17
*************************************************/

#ifndef _HR7P153_H
#define _HR7P153_H

/*      Register Map      */
static volatile unsigned char section1 IAD             @ 0xFF80 ;
static volatile unsigned char section1 IAAL            @ 0xFF81 ;
static volatile unsigned char section1 IAAH            @ 0xFF82 ;
static volatile unsigned char section1 PSW             @ 0xFF84 ;
static volatile unsigned char section1 AREG            @ 0xFF85 ;
static volatile unsigned char section1 IAPC            @ 0xFF86 ;
static volatile unsigned char section1 FRAL            @ 0xFF87 ;
static volatile unsigned char section1 FRAH            @ 0xFF88 ;
static volatile unsigned char section1 ROMDL           @ 0xFF89 ;
static volatile unsigned char section1 ROMDH           @ 0xFF8A ;
static volatile unsigned char section1 PCRL            @ 0xFF8B ;
static          unsigned char section1 PCRH            @ 0xFF8C ;
static volatile unsigned char section1 PA              @ 0xFF8E ;
static volatile unsigned char section1 PAT             @ 0xFF8F ;
static volatile unsigned char section1 PB              @ 0xFF90 ;
static volatile unsigned char section1 PBT             @ 0xFF91 ;
static volatile unsigned char section1 N_PAD           @ 0xFF94 ;
static volatile unsigned char section1 N_PBD           @ 0xFF95 ;
static volatile unsigned char section1 N_PAU           @ 0xFF96 ;
static volatile unsigned char section1 N_PBU           @ 0xFF97 ;
static volatile unsigned char section1 PINTS           @ 0xFF9B ;
static volatile unsigned char section1 ANS             @ 0xFF9C ;
static volatile unsigned char section1 INTF0           @ 0xFF9D ;
static volatile unsigned char section1 INTE0           @ 0xFF9E ;
static volatile unsigned char section1 INTC0           @ 0xFF9F ;
static volatile unsigned char section1 INTG            @ 0xFFA0 ;
static volatile unsigned char section1 LVDC            @ 0xFFA1 ;
static volatile unsigned char section1 INTF1           @ 0xFFA2 ;
static volatile unsigned char section1 INTE1           @ 0xFFA3 ;
static volatile unsigned char section1 INTC1           @ 0xFFA4 ;
static volatile unsigned char section1 OSCCAL          @ 0xFFA5 ;
static volatile unsigned char section1 WDTCAL          @ 0xFFA6 ;
static volatile unsigned char section1 PWRC            @ 0xFFA7 ;
static volatile unsigned char section1 OSCC            @ 0xFFA8 ;
static volatile unsigned char section1 WKDC            @ 0xFFA9 ;
static volatile unsigned char section1 OSCP            @ 0xFFAA ;
static volatile unsigned char section1 WDTC            @ 0xFFAB ;
static volatile unsigned char section1 PWEN            @ 0xFFAC ;
static volatile unsigned char section1 WDTP            @ 0xFFB0 ;
static volatile unsigned char section1 T8P1            @ 0xFFB2 ;
static volatile unsigned char section1 T8P1C           @ 0xFFB3 ;
static volatile unsigned char section1 T8P1P           @ 0xFFB4 ;
static volatile unsigned char section1 T8P1R           @ 0xFFB5 ;
static volatile unsigned char section1 T8P1PMC         @ 0xFFB6 ;
static volatile unsigned char section1 T8P1OC          @ 0xFFB7 ;
static volatile unsigned char section1 T8P2            @ 0xFFB8 ;
static volatile unsigned char section1 T8P2C           @ 0xFFB9 ;
static volatile unsigned char section1 T8P2P           @ 0xFFBA ;
static volatile unsigned char section1 T8P2R           @ 0xFFBB ;
static volatile unsigned char section1 T8P2PMC         @ 0xFFBC ;
static volatile unsigned char section1 T8P2OC          @ 0xFFBD ;
static volatile unsigned char section1 T8P1PDT         @ 0xFFBE ;
static volatile unsigned char section1 T8P2PDT         @ 0xFFBF ;
static volatile unsigned char section1 T8P1PEX         @ 0xFFC0 ;
static volatile unsigned char section1 T8P2PEX         @ 0xFFC1 ;
static volatile unsigned char section1 ADCCL           @ 0xFFC6 ;
static volatile unsigned char section1 ADCCH           @ 0xFFC7 ;
static volatile unsigned char section1 ADCRL           @ 0xFFC8 ;
static volatile unsigned char section1 ADCRH           @ 0xFFC9 ;
static volatile unsigned char section1 ADCTR           @ 0xFFCA ;
static volatile unsigned char section1 CALPROT         @ 0xFFCF ;

/*      IAD bits      */
static volatile section1 sbit IAD0            @ (unsigned) &IAD * 8 + 0 ;
static volatile section1 sbit IAD1            @ (unsigned) &IAD * 8 + 1 ;
static volatile section1 sbit IAD2            @ (unsigned) &IAD * 8 + 2 ;
static volatile section1 sbit IAD3            @ (unsigned) &IAD * 8 + 3 ;
static volatile section1 sbit IAD4            @ (unsigned) &IAD * 8 + 4 ;
static volatile section1 sbit IAD5            @ (unsigned) &IAD * 8 + 5 ;
static volatile section1 sbit IAD6            @ (unsigned) &IAD * 8 + 6 ;
static volatile section1 sbit IAD7            @ (unsigned) &IAD * 8 + 7 ;

/*      IAAL bits      */
static volatile section1 sbit IAA0            @ (unsigned) &IAAL * 8 + 0 ;
static volatile section1 sbit IAA1            @ (unsigned) &IAAL * 8 + 1 ;
static volatile section1 sbit IAA2            @ (unsigned) &IAAL * 8 + 2 ;
static volatile section1 sbit IAA3            @ (unsigned) &IAAL * 8 + 3 ;
static volatile section1 sbit IAA4            @ (unsigned) &IAAL * 8 + 4 ;
static volatile section1 sbit IAA5            @ (unsigned) &IAAL * 8 + 5 ;
static volatile section1 sbit IAA6            @ (unsigned) &IAAL * 8 + 6 ;
static volatile section1 sbit IAA7            @ (unsigned) &IAAL * 8 + 7 ;

/*      IAAH bits      */
static volatile section1 sbit IAA8            @ (unsigned) &IAAH * 8 + 0 ;
static volatile section1 sbit IAA9            @ (unsigned) &IAAH * 8 + 1 ;
static volatile section1 sbit IAA10           @ (unsigned) &IAAH * 8 + 2 ;
static volatile section1 sbit IAA11           @ (unsigned) &IAAH * 8 + 3 ;
static volatile section1 sbit IAA12           @ (unsigned) &IAAH * 8 + 4 ;
static volatile section1 sbit IAA13           @ (unsigned) &IAAH * 8 + 5 ;
static volatile section1 sbit IAA14           @ (unsigned) &IAAH * 8 + 6 ;
static volatile section1 sbit IAA15           @ (unsigned) &IAAH * 8 + 7 ;

/*      PSW bits      */
static volatile section1 sbit C               @ (unsigned) &PSW * 8 + 0 ;
static volatile section1 sbit DC              @ (unsigned) &PSW * 8 + 1 ;
static volatile section1 sbit Z               @ (unsigned) &PSW * 8 + 2 ;
static volatile section1 sbit OV              @ (unsigned) &PSW * 8 + 3 ;
static volatile section1 sbit N               @ (unsigned) &PSW * 8 + 4 ;
static volatile section1 sbit OF              @ (unsigned) &PSW * 8 + 5 ;
static volatile section1 sbit UF              @ (unsigned) &PSW * 8 + 6 ;

/*      AREG bits      */
static volatile section1 sbit AREG0           @ (unsigned) &AREG * 8 + 0 ;
static volatile section1 sbit AREG1           @ (unsigned) &AREG * 8 + 1 ;
static volatile section1 sbit AREG2           @ (unsigned) &AREG * 8 + 2 ;
static volatile section1 sbit AREG3           @ (unsigned) &AREG * 8 + 3 ;
static volatile section1 sbit AREG4           @ (unsigned) &AREG * 8 + 4 ;
static volatile section1 sbit AREG5           @ (unsigned) &AREG * 8 + 5 ;
static volatile section1 sbit AREG6           @ (unsigned) &AREG * 8 + 6 ;
static volatile section1 sbit AREG7           @ (unsigned) &AREG * 8 + 7 ;

/*      IAPC bits      */
static volatile section1 sbit IAPGO           @ (unsigned) &IAPC * 8 + 1 ;
static volatile section1 sbit IAPEN           @ (unsigned) &IAPC * 8 + 7 ;

/*      FRAL bits      */
static volatile section1 sbit FRA0            @ (unsigned) &FRAL * 8 + 0 ;
static volatile section1 sbit FRA1            @ (unsigned) &FRAL * 8 + 1 ;
static volatile section1 sbit FRA2            @ (unsigned) &FRAL * 8 + 2 ;
static volatile section1 sbit FRA3            @ (unsigned) &FRAL * 8 + 3 ;
static volatile section1 sbit FRA4            @ (unsigned) &FRAL * 8 + 4 ;
static volatile section1 sbit FRA5            @ (unsigned) &FRAL * 8 + 5 ;
static volatile section1 sbit FRA6            @ (unsigned) &FRAL * 8 + 6 ;
static volatile section1 sbit FRA7            @ (unsigned) &FRAL * 8 + 7 ;

/*      FRAH bits      */
static volatile section1 sbit FRA8            @ (unsigned) &FRAH * 8 + 0 ;
static volatile section1 sbit FRA9            @ (unsigned) &FRAH * 8 + 1 ;
static volatile section1 sbit FRA10           @ (unsigned) &FRAH * 8 + 2 ;
static volatile section1 sbit FRA11           @ (unsigned) &FRAH * 8 + 3 ;
static volatile section1 sbit FRA12           @ (unsigned) &FRAH * 8 + 4 ;
static volatile section1 sbit FRA13           @ (unsigned) &FRAH * 8 + 5 ;
static volatile section1 sbit FRA14           @ (unsigned) &FRAH * 8 + 6 ;
static volatile section1 sbit FRA15           @ (unsigned) &FRAH * 8 + 7 ;

/*      ROMDL bits      */
static volatile section1 sbit ROMD0           @ (unsigned) &ROMDL * 8 + 0 ;
static volatile section1 sbit ROMD1           @ (unsigned) &ROMDL * 8 + 1 ;
static volatile section1 sbit ROMD2           @ (unsigned) &ROMDL * 8 + 2 ;
static volatile section1 sbit ROMD3           @ (unsigned) &ROMDL * 8 + 3 ;
static volatile section1 sbit ROMD4           @ (unsigned) &ROMDL * 8 + 4 ;
static volatile section1 sbit ROMD5           @ (unsigned) &ROMDL * 8 + 5 ;
static volatile section1 sbit ROMD6           @ (unsigned) &ROMDL * 8 + 6 ;
static volatile section1 sbit ROMD7           @ (unsigned) &ROMDL * 8 + 7 ;

/*      ROMDH bits      */
static volatile section1 sbit ROMD8           @ (unsigned) &ROMDH * 8 + 0 ;
static volatile section1 sbit ROMD9           @ (unsigned) &ROMDH * 8 + 1 ;
static volatile section1 sbit ROMD10          @ (unsigned) &ROMDH * 8 + 2 ;
static volatile section1 sbit ROMD11          @ (unsigned) &ROMDH * 8 + 3 ;
static volatile section1 sbit ROMD12          @ (unsigned) &ROMDH * 8 + 4 ;
static volatile section1 sbit ROMD13          @ (unsigned) &ROMDH * 8 + 5 ;
static volatile section1 sbit ROMD14          @ (unsigned) &ROMDH * 8 + 6 ;
static volatile section1 sbit ROMD15          @ (unsigned) &ROMDH * 8 + 7 ;

/*      PCRL bits      */
static volatile section1 sbit PCR0            @ (unsigned) &PCRL * 8 + 0 ;
static volatile section1 sbit PCR1            @ (unsigned) &PCRL * 8 + 1 ;
static volatile section1 sbit PCR2            @ (unsigned) &PCRL * 8 + 2 ;
static volatile section1 sbit PCR3            @ (unsigned) &PCRL * 8 + 3 ;
static volatile section1 sbit PCR4            @ (unsigned) &PCRL * 8 + 4 ;
static volatile section1 sbit PCR5            @ (unsigned) &PCRL * 8 + 5 ;
static volatile section1 sbit PCR6            @ (unsigned) &PCRL * 8 + 6 ;
static volatile section1 sbit PCR7            @ (unsigned) &PCRL * 8 + 7 ;

/*      PCRH bits      */
static volatile section1 sbit PCR8            @ (unsigned) &PCRH * 8 + 0 ;
static volatile section1 sbit PCR9            @ (unsigned) &PCRH * 8 + 1 ;
static volatile section1 sbit PCR10           @ (unsigned) &PCRH * 8 + 2 ;

/*      PA bits      */
static volatile section1 sbit PA0             @ (unsigned) &PA * 8 + 0 ;
static volatile section1 sbit PA1             @ (unsigned) &PA * 8 + 1 ;
static volatile section1 sbit PA2             @ (unsigned) &PA * 8 + 2 ;
static volatile section1 sbit PA3             @ (unsigned) &PA * 8 + 3 ;
static volatile section1 sbit PA4             @ (unsigned) &PA * 8 + 4 ;
static volatile section1 sbit PA5             @ (unsigned) &PA * 8 + 5 ;
static volatile section1 sbit PA6             @ (unsigned) &PA * 8 + 6 ;
static volatile section1 sbit PA7             @ (unsigned) &PA * 8 + 7 ;

/*      PAT bits      */
static volatile section1 sbit PAT0            @ (unsigned) &PAT * 8 + 0 ;
static volatile section1 sbit PAT1            @ (unsigned) &PAT * 8 + 1 ;
static volatile section1 sbit PAT2            @ (unsigned) &PAT * 8 + 2 ;
static volatile section1 sbit PAT3            @ (unsigned) &PAT * 8 + 3 ;
static volatile section1 sbit PAT4            @ (unsigned) &PAT * 8 + 4 ;
static volatile section1 sbit PAT5            @ (unsigned) &PAT * 8 + 5 ;
static volatile section1 sbit PAT6            @ (unsigned) &PAT * 8 + 6 ;
static volatile section1 sbit PAT7            @ (unsigned) &PAT * 8 + 7 ;

/*      PB bits      */
static volatile section1 sbit PB0             @ (unsigned) &PB * 8 + 0 ;
static volatile section1 sbit PB1             @ (unsigned) &PB * 8 + 1 ;
static volatile section1 sbit PB2             @ (unsigned) &PB * 8 + 2 ;
static volatile section1 sbit PB3             @ (unsigned) &PB * 8 + 3 ;
static volatile section1 sbit PB4             @ (unsigned) &PB * 8 + 4 ;
static volatile section1 sbit PB5             @ (unsigned) &PB * 8 + 5 ;

/*      PBT bits      */
static volatile section1 sbit PBT0            @ (unsigned) &PBT * 8 + 0 ;
static volatile section1 sbit PBT1            @ (unsigned) &PBT * 8 + 1 ;
static volatile section1 sbit PBT2            @ (unsigned) &PBT * 8 + 2 ;
static volatile section1 sbit PBT3            @ (unsigned) &PBT * 8 + 3 ;
static volatile section1 sbit PBT4            @ (unsigned) &PBT * 8 + 4 ;
static volatile section1 sbit PBT5            @ (unsigned) &PBT * 8 + 5 ;

/*      N_PAD bits      */
static volatile section1 sbit N_PAD0          @ (unsigned) &N_PAD * 8 + 0 ;
static volatile section1 sbit N_PAD1          @ (unsigned) &N_PAD * 8 + 1 ;
static volatile section1 sbit N_PAD2          @ (unsigned) &N_PAD * 8 + 2 ;
static volatile section1 sbit N_PAD4          @ (unsigned) &N_PAD * 8 + 4 ;
static volatile section1 sbit N_PAD5          @ (unsigned) &N_PAD * 8 + 5 ;
static volatile section1 sbit N_PAD6          @ (unsigned) &N_PAD * 8 + 6 ;
static volatile section1 sbit N_PAD7          @ (unsigned) &N_PAD * 8 + 7 ;

/*      N_PBD bits      */
static volatile section1 sbit N_PBD0          @ (unsigned) &N_PBD * 8 + 0 ;
static volatile section1 sbit N_PBD1          @ (unsigned) &N_PBD * 8 + 1 ;
static volatile section1 sbit N_PBD2          @ (unsigned) &N_PBD * 8 + 2 ;
static volatile section1 sbit N_PBD3          @ (unsigned) &N_PBD * 8 + 3 ;
static volatile section1 sbit N_PBD4          @ (unsigned) &N_PBD * 8 + 4 ;
static volatile section1 sbit PLCS            @ (unsigned) &N_PBD * 8 + 5 ;

/*      N_PAU bits      */
static volatile section1 sbit N_PAU0          @ (unsigned) &N_PAU * 8 + 0 ;
static volatile section1 sbit N_PAU1          @ (unsigned) &N_PAU * 8 + 1 ;
static volatile section1 sbit N_PAU2          @ (unsigned) &N_PAU * 8 + 2 ;
static volatile section1 sbit N_PAU3          @ (unsigned) &N_PAU * 8 + 3 ;
static volatile section1 sbit N_PAU4          @ (unsigned) &N_PAU * 8 + 4 ;
static volatile section1 sbit N_PAU5          @ (unsigned) &N_PAU * 8 + 5 ;
static volatile section1 sbit N_PAU6          @ (unsigned) &N_PAU * 8 + 6 ;
static volatile section1 sbit N_PAU7          @ (unsigned) &N_PAU * 8 + 7 ;

/*      N_PBU bits      */
static volatile section1 sbit N_PBU0          @ (unsigned) &N_PBU * 8 + 0 ;
static volatile section1 sbit N_PBU1          @ (unsigned) &N_PBU * 8 + 1 ;
static volatile section1 sbit N_PBU2          @ (unsigned) &N_PBU * 8 + 2 ;
static volatile section1 sbit N_PBU3          @ (unsigned) &N_PBU * 8 + 3 ;
static volatile section1 sbit N_PBU4          @ (unsigned) &N_PBU * 8 + 4 ;
static volatile section1 sbit N_PBU5          @ (unsigned) &N_PBU * 8 + 5 ;

/*      PINTS bits      */
// static volatile section1 sbit PINT0S0         @ (unsigned) &PINTS * 8 + 0 ;
// static volatile section1 sbit PINT0S1         @ (unsigned) &PINTS * 8 + 1 ;
// static volatile section1 sbit PINT1S0         @ (unsigned) &PINTS * 8 + 2 ;
// static volatile section1 sbit PINT1S1         @ (unsigned) &PINTS * 8 + 3 ;
// static volatile section1 sbit PINT2S0         @ (unsigned) &PINTS * 8 + 4 ;
// static volatile section1 sbit PINT2S1         @ (unsigned) &PINTS * 8 + 5 ;
// static volatile section1 sbit PINT3S0         @ (unsigned) &PINTS * 8 + 6 ;
// static volatile section1 sbit PINT3S1         @ (unsigned) &PINTS * 8 + 7 ;

/*      ANS bits      */
static volatile section1 sbit ANPA0           @ (unsigned) &ANS * 8 + 0 ;
static volatile section1 sbit ANPA1           @ (unsigned) &ANS * 8 + 1 ;
static volatile section1 sbit ANPA2           @ (unsigned) &ANS * 8 + 2 ;
static volatile section1 sbit ANPB0           @ (unsigned) &ANS * 8 + 3 ;
static volatile section1 sbit ANPB1           @ (unsigned) &ANS * 8 + 4 ;
static volatile section1 sbit ANPA7           @ (unsigned) &ANS * 8 + 5 ;
static volatile section1 sbit PWM10NS         @ (unsigned) &ANS * 8 + 6 ;
static volatile section1 sbit PWM20NS         @ (unsigned) &ANS * 8 + 7 ;

/*      INTF0 bits      */
static volatile section1 sbit KIF             @ (unsigned) &INTF0 * 8 + 0 ;
static volatile section1 sbit T8P1TIF         @ (unsigned) &INTF0 * 8 + 1 ;
static volatile section1 sbit T8P2TIF         @ (unsigned) &INTF0 * 8 + 2 ;
static volatile section1 sbit LVDIF           @ (unsigned) &INTF0 * 8 + 4 ;
static volatile section1 sbit ADIF            @ (unsigned) &INTF0 * 8 + 5 ;
static volatile section1 sbit T8P1PIF         @ (unsigned) &INTF0 * 8 + 6 ;
static volatile section1 sbit T8P2PIF         @ (unsigned) &INTF0 * 8 + 7 ;

/*      INTE0 bits      */
static volatile section1 sbit KIE             @ (unsigned) &INTE0 * 8 + 0 ;
static volatile section1 sbit T8P1TIE         @ (unsigned) &INTE0 * 8 + 1 ;
static volatile section1 sbit T8P2TIE         @ (unsigned) &INTE0 * 8 + 2 ;
static volatile section1 sbit LVDIE           @ (unsigned) &INTE0 * 8 + 4 ;
static volatile section1 sbit ADIE            @ (unsigned) &INTE0 * 8 + 5 ;
static volatile section1 sbit T8P1PIE         @ (unsigned) &INTE0 * 8 + 6 ;
static volatile section1 sbit T8P2PIE         @ (unsigned) &INTE0 * 8 + 7 ;

/*      INTC0 bits      */
static volatile section1 sbit KMSK0           @ (unsigned) &INTC0 * 8 + 0 ;
static volatile section1 sbit KMSK1           @ (unsigned) &INTC0 * 8 + 1 ;
static volatile section1 sbit KMSK2           @ (unsigned) &INTC0 * 8 + 2 ;
static volatile section1 sbit KMSK3           @ (unsigned) &INTC0 * 8 + 3 ;
static volatile section1 sbit KMSK4           @ (unsigned) &INTC0 * 8 + 4 ;
static volatile section1 sbit KMSK5           @ (unsigned) &INTC0 * 8 + 5 ;
static volatile section1 sbit KMSK6           @ (unsigned) &INTC0 * 8 + 6 ;
static volatile section1 sbit KMSK7           @ (unsigned) &INTC0 * 8 + 7 ;

/*      INTG bits      */
static volatile section1 sbit SOFTIF          @ (unsigned) &INTG * 8 + 1 ;
static volatile section1 sbit GIE             @ (unsigned) &INTG * 8 + 7 ;

/*      LVDC bits      */
static volatile section1 sbit LVDV0           @ (unsigned) &LVDC * 8 + 0 ;
static volatile section1 sbit LVDV1           @ (unsigned) &LVDC * 8 + 1 ;
static volatile section1 sbit LVDEN           @ (unsigned) &LVDC * 8 + 4 ;
static volatile section1 sbit LVDLS           @ (unsigned) &LVDC * 8 + 7 ;

/*      INTF1 bits      */
static volatile section1 sbit PIF0            @ (unsigned) &INTF1 * 8 + 0 ;
static volatile section1 sbit PIF1            @ (unsigned) &INTF1 * 8 + 1 ;
static volatile section1 sbit PIF2            @ (unsigned) &INTF1 * 8 + 2 ;
static volatile section1 sbit PIF3            @ (unsigned) &INTF1 * 8 + 3 ;

/*      INTE1 bits      */
static volatile section1 sbit PIE0            @ (unsigned) &INTE1 * 8 + 0 ;
static volatile section1 sbit PIE1            @ (unsigned) &INTE1 * 8 + 1 ;
static volatile section1 sbit PIE2            @ (unsigned) &INTE1 * 8 + 2 ;
static volatile section1 sbit PIE3            @ (unsigned) &INTE1 * 8 + 3 ;

/*      INTC1 bits      */
static volatile section1 sbit PEG0            @ (unsigned) &INTC1 * 8 + 0 ;
static volatile section1 sbit PEG1            @ (unsigned) &INTC1 * 8 + 1 ;
static volatile section1 sbit PEG2            @ (unsigned) &INTC1 * 8 + 2 ;
static volatile section1 sbit PEG3            @ (unsigned) &INTC1 * 8 + 3 ;

/*      OSCCAL bits      */
static volatile section1 sbit OSCCAL0         @ (unsigned) &OSCCAL * 8 + 0 ;
static volatile section1 sbit OSCCAL1         @ (unsigned) &OSCCAL * 8 + 1 ;
static volatile section1 sbit OSCCAL2         @ (unsigned) &OSCCAL * 8 + 2 ;
static volatile section1 sbit OSCCAL3         @ (unsigned) &OSCCAL * 8 + 3 ;
static volatile section1 sbit OSCCAL4         @ (unsigned) &OSCCAL * 8 + 4 ;
static volatile section1 sbit OSCCAL5         @ (unsigned) &OSCCAL * 8 + 5 ;
static volatile section1 sbit OSCCAL6         @ (unsigned) &OSCCAL * 8 + 6 ;
static volatile section1 sbit OSCCAL7         @ (unsigned) &OSCCAL * 8 + 7 ;

/*      WDTCAL bits      */
static volatile section1 sbit WDTCAL0         @ (unsigned) &WDTCAL * 8 + 0 ;
static volatile section1 sbit WDTCAL1         @ (unsigned) &WDTCAL * 8 + 1 ;
static volatile section1 sbit WDTCAL2         @ (unsigned) &WDTCAL * 8 + 2 ;
static volatile section1 sbit WDTCAL3         @ (unsigned) &WDTCAL * 8 + 3 ;
static volatile section1 sbit WDTCAL4         @ (unsigned) &WDTCAL * 8 + 4 ;
static volatile section1 sbit WDTCAL5         @ (unsigned) &WDTCAL * 8 + 5 ;
static volatile section1 sbit WDTCAL6         @ (unsigned) &WDTCAL * 8 + 6 ;
static volatile section1 sbit WDTCAL7         @ (unsigned) &WDTCAL * 8 + 7 ;

/*      PWRC bits      */
static volatile section1 sbit N_BOR           @ (unsigned) &PWRC * 8 + 0 ;
static volatile section1 sbit N_POR           @ (unsigned) &PWRC * 8 + 1 ;
static volatile section1 sbit N_PD            @ (unsigned) &PWRC * 8 + 2 ;
static volatile section1 sbit N_TO            @ (unsigned) &PWRC * 8 + 3 ;
static volatile section1 sbit N_RSTI          @ (unsigned) &PWRC * 8 + 4 ;
static volatile section1 sbit VRST0           @ (unsigned) &PWRC * 8 + 5 ;
static volatile section1 sbit VRST1           @ (unsigned) &PWRC * 8 + 6 ;
static volatile section1 sbit LPM             @ (unsigned) &PWRC * 8 + 7 ;

/*      OSCC bits      */
static volatile section1 sbit LPOSCF          @ (unsigned) &OSCC * 8 + 0 ;
static volatile section1 sbit HSOSCF          @ (unsigned) &OSCC * 8 + 1 ;
static volatile section1 sbit WDTOSCF         @ (unsigned) &OSCC * 8 + 2 ;
static volatile section1 sbit FOSCS0          @ (unsigned) &OSCC * 8 + 4 ;
static volatile section1 sbit FOSCS1          @ (unsigned) &OSCC * 8 + 5 ;
static volatile section1 sbit FOSCS2          @ (unsigned) &OSCC * 8 + 6 ;
static volatile section1 sbit CLKSS           @ (unsigned) &OSCC * 8 + 7 ;

/*      WKDC bits      */
static volatile section1 sbit WKDC0           @ (unsigned) &WKDC * 8 + 0 ;
static volatile section1 sbit WKDC1           @ (unsigned) &WKDC * 8 + 1 ;
static volatile section1 sbit WKDC2           @ (unsigned) &WKDC * 8 + 2 ;
static volatile section1 sbit WKDC3           @ (unsigned) &WKDC * 8 + 3 ;
static volatile section1 sbit WKDC4           @ (unsigned) &WKDC * 8 + 4 ;
static volatile section1 sbit WKDC5           @ (unsigned) &WKDC * 8 + 5 ;
static volatile section1 sbit WKDC6           @ (unsigned) &WKDC * 8 + 6 ;
static volatile section1 sbit WKDC7           @ (unsigned) &WKDC * 8 + 7 ;

/*      OSCP bits      */
static volatile section1 sbit OSCP0           @ (unsigned) &OSCP * 8 + 0 ;
static volatile section1 sbit OSCP1           @ (unsigned) &OSCP * 8 + 1 ;
static volatile section1 sbit OSCP2           @ (unsigned) &OSCP * 8 + 2 ;
static volatile section1 sbit OSCP3           @ (unsigned) &OSCP * 8 + 3 ;
static volatile section1 sbit OSCP4           @ (unsigned) &OSCP * 8 + 4 ;
static volatile section1 sbit OSCP5           @ (unsigned) &OSCP * 8 + 5 ;
static volatile section1 sbit OSCP6           @ (unsigned) &OSCP * 8 + 6 ;
static volatile section1 sbit OSCP7           @ (unsigned) &OSCP * 8 + 7 ;

/*      WDTC bits      */
static volatile section1 sbit WDTPRS0         @ (unsigned) &WDTC * 8 + 0 ;
static volatile section1 sbit WDTPRS1         @ (unsigned) &WDTC * 8 + 1 ;
static volatile section1 sbit WDTPRS2         @ (unsigned) &WDTC * 8 + 2 ;
static volatile section1 sbit WDTPRS3         @ (unsigned) &WDTC * 8 + 3 ;
static volatile section1 sbit WDTPRE          @ (unsigned) &WDTC * 8 + 4 ;
static volatile section1 sbit WDTCKS          @ (unsigned) &WDTC * 8 + 7 ;

/*      PWEN bits      */
static volatile section1 sbit RCEN            @ (unsigned) &PWEN * 8 + 1 ;
static volatile section1 sbit SW_LP           @ (unsigned) &PWEN * 8 + 4 ;
static volatile section1 sbit SW_HS           @ (unsigned) &PWEN * 8 + 5 ;
static volatile section1 sbit SW_WDT          @ (unsigned) &PWEN * 8 + 6 ;

/*      WDTP bits      */
static volatile section1 sbit WDTP0           @ (unsigned) &WDTP * 8 + 0 ;
static volatile section1 sbit WDTP1           @ (unsigned) &WDTP * 8 + 1 ;
static volatile section1 sbit WDTP2           @ (unsigned) &WDTP * 8 + 2 ;
static volatile section1 sbit WDTP3           @ (unsigned) &WDTP * 8 + 3 ;
static volatile section1 sbit WDTP4           @ (unsigned) &WDTP * 8 + 4 ;
static volatile section1 sbit WDTP5           @ (unsigned) &WDTP * 8 + 5 ;
static volatile section1 sbit WDTP6           @ (unsigned) &WDTP * 8 + 6 ;
static volatile section1 sbit WDTP7           @ (unsigned) &WDTP * 8 + 7 ;

/*      T8P1 bits      */
static volatile section1 sbit T8P10           @ (unsigned) &T8P1 * 8 + 0 ;
static volatile section1 sbit T8P11           @ (unsigned) &T8P1 * 8 + 1 ;
static volatile section1 sbit T8P12           @ (unsigned) &T8P1 * 8 + 2 ;
static volatile section1 sbit T8P13           @ (unsigned) &T8P1 * 8 + 3 ;
static volatile section1 sbit T8P14           @ (unsigned) &T8P1 * 8 + 4 ;
static volatile section1 sbit T8P15           @ (unsigned) &T8P1 * 8 + 5 ;
static volatile section1 sbit T8P16           @ (unsigned) &T8P1 * 8 + 6 ;
static volatile section1 sbit T8P17           @ (unsigned) &T8P1 * 8 + 7 ;

/*      T8P1C bits      */
static volatile section1 sbit T8P1PRS0        @ (unsigned) &T8P1C * 8 + 0 ;
static volatile section1 sbit T8P1PRS1        @ (unsigned) &T8P1C * 8 + 1 ;
static volatile section1 sbit T8P1E           @ (unsigned) &T8P1C * 8 + 2 ;
static volatile section1 sbit T8P1POS0        @ (unsigned) &T8P1C * 8 + 3 ;
static volatile section1 sbit T8P1POS1        @ (unsigned) &T8P1C * 8 + 4 ;
static volatile section1 sbit T8P1POS2        @ (unsigned) &T8P1C * 8 + 5 ;
static volatile section1 sbit T8P1POS3        @ (unsigned) &T8P1C * 8 + 6 ;
static volatile section1 sbit T8P1M           @ (unsigned) &T8P1C * 8 + 7 ;

/*      T8P1P bits      */
static volatile section1 sbit T8P1P0          @ (unsigned) &T8P1P * 8 + 0 ;
static volatile section1 sbit T8P1P1          @ (unsigned) &T8P1P * 8 + 1 ;
static volatile section1 sbit T8P1P2          @ (unsigned) &T8P1P * 8 + 2 ;
static volatile section1 sbit T8P1P3          @ (unsigned) &T8P1P * 8 + 3 ;
static volatile section1 sbit T8P1P4          @ (unsigned) &T8P1P * 8 + 4 ;
static volatile section1 sbit T8P1P5          @ (unsigned) &T8P1P * 8 + 5 ;
static volatile section1 sbit T8P1P6          @ (unsigned) &T8P1P * 8 + 6 ;
static volatile section1 sbit T8P1P7          @ (unsigned) &T8P1P * 8 + 7 ;

/*      T8P1R bits      */
static volatile section1 sbit T8P1R0          @ (unsigned) &T8P1R * 8 + 0 ;
static volatile section1 sbit T8P1R1          @ (unsigned) &T8P1R * 8 + 1 ;
static volatile section1 sbit T8P1R2          @ (unsigned) &T8P1R * 8 + 2 ;
static volatile section1 sbit T8P1R3          @ (unsigned) &T8P1R * 8 + 3 ;
static volatile section1 sbit T8P1R4          @ (unsigned) &T8P1R * 8 + 4 ;
static volatile section1 sbit T8P1R5          @ (unsigned) &T8P1R * 8 + 5 ;
static volatile section1 sbit T8P1R6          @ (unsigned) &T8P1R * 8 + 6 ;
static volatile section1 sbit T8P1R7          @ (unsigned) &T8P1R * 8 + 7 ;

/*      T8P1PMC bits      */
static volatile section1 sbit T8P1PMS         @ (unsigned) &T8P1PMC * 8 + 0 ;
static volatile section1 sbit T8P1RS          @ (unsigned) &T8P1PMC * 8 + 1 ;

/*      T8P1OC bits      */
static volatile section1 sbit T8P1PEN0        @ (unsigned) &T8P1OC * 8 + 0 ;
static volatile section1 sbit T8P1PEN1        @ (unsigned) &T8P1OC * 8 + 1 ;
static volatile section1 sbit T8P1NEN0        @ (unsigned) &T8P1OC * 8 + 2 ;
static volatile section1 sbit T8P1NEN1        @ (unsigned) &T8P1OC * 8 + 3 ;
static volatile section1 sbit T8P1RE0         @ (unsigned) &T8P1OC * 8 + 4 ;
static volatile section1 sbit T8P1RE1         @ (unsigned) &T8P1OC * 8 + 5 ;
static volatile section1 sbit T8P1REX         @ (unsigned) &T8P1OC * 8 + 6 ;
static volatile section1 sbit T8P1TRN         @ (unsigned) &T8P1OC * 8 + 7 ;

/*      T8P2 bits      */
static volatile section1 sbit T8P20           @ (unsigned) &T8P2 * 8 + 0 ;
static volatile section1 sbit T8P21           @ (unsigned) &T8P2 * 8 + 1 ;
static volatile section1 sbit T8P22           @ (unsigned) &T8P2 * 8 + 2 ;
static volatile section1 sbit T8P23           @ (unsigned) &T8P2 * 8 + 3 ;
static volatile section1 sbit T8P24           @ (unsigned) &T8P2 * 8 + 4 ;
static volatile section1 sbit T8P25           @ (unsigned) &T8P2 * 8 + 5 ;
static volatile section1 sbit T8P26           @ (unsigned) &T8P2 * 8 + 6 ;
static volatile section1 sbit T8P27           @ (unsigned) &T8P2 * 8 + 7 ;

/*      T8P2C bits      */
static volatile section1 sbit T8P2PRS0        @ (unsigned) &T8P2C * 8 + 0 ;
static volatile section1 sbit T8P2PRS1        @ (unsigned) &T8P2C * 8 + 1 ;
static volatile section1 sbit T8P2E           @ (unsigned) &T8P2C * 8 + 2 ;
static volatile section1 sbit T8P2POS0        @ (unsigned) &T8P2C * 8 + 3 ;
static volatile section1 sbit T8P2POS1        @ (unsigned) &T8P2C * 8 + 4 ;
static volatile section1 sbit T8P2POS2        @ (unsigned) &T8P2C * 8 + 5 ;
static volatile section1 sbit T8P2POS3        @ (unsigned) &T8P2C * 8 + 6 ;
static volatile section1 sbit T8P2M           @ (unsigned) &T8P2C * 8 + 7 ;

/*      T8P2P bits      */
static volatile section1 sbit T8P2PL0         @ (unsigned) &T8P2P * 8 + 0 ;
static volatile section1 sbit T8P2PL1         @ (unsigned) &T8P2P * 8 + 1 ;
static volatile section1 sbit T8P2PL2         @ (unsigned) &T8P2P * 8 + 2 ;
static volatile section1 sbit T8P2PL3         @ (unsigned) &T8P2P * 8 + 3 ;
static volatile section1 sbit T8P2PL4         @ (unsigned) &T8P2P * 8 + 4 ;
static volatile section1 sbit T8P2PL5         @ (unsigned) &T8P2P * 8 + 5 ;
static volatile section1 sbit T8P2PL6         @ (unsigned) &T8P2P * 8 + 6 ;
static volatile section1 sbit T8P2PL7         @ (unsigned) &T8P2P * 8 + 7 ;

/*      T8P2R bits      */
static volatile section1 sbit T8P2RL0         @ (unsigned) &T8P2R * 8 + 0 ;
static volatile section1 sbit T8P2RL1         @ (unsigned) &T8P2R * 8 + 1 ;
static volatile section1 sbit T8P2RL2         @ (unsigned) &T8P2R * 8 + 2 ;
static volatile section1 sbit T8P2RL3         @ (unsigned) &T8P2R * 8 + 3 ;
static volatile section1 sbit T8P2RL4         @ (unsigned) &T8P2R * 8 + 4 ;
static volatile section1 sbit T8P2RL5         @ (unsigned) &T8P2R * 8 + 5 ;
static volatile section1 sbit T8P2RL6         @ (unsigned) &T8P2R * 8 + 6 ;
static volatile section1 sbit T8P2RL7         @ (unsigned) &T8P2R * 8 + 7 ;

/*      T8P2PMC bits      */
static volatile section1 sbit T8P2PMS         @ (unsigned) &T8P2PMC * 8 + 0 ;
static volatile section1 sbit T8P2RS          @ (unsigned) &T8P2PMC * 8 + 1 ;

/*      T8P2OC bits      */
static volatile section1 sbit T8P2PEN0        @ (unsigned) &T8P2OC * 8 + 0 ;
static volatile section1 sbit T8P2PEN1        @ (unsigned) &T8P2OC * 8 + 1 ;
static volatile section1 sbit T8P2NEN0        @ (unsigned) &T8P2OC * 8 + 2 ;
static volatile section1 sbit T8P2NEN1        @ (unsigned) &T8P2OC * 8 + 3 ;
static volatile section1 sbit T8P2RE0         @ (unsigned) &T8P2OC * 8 + 4 ;
static volatile section1 sbit T8P2RE1         @ (unsigned) &T8P2OC * 8 + 5 ;
static volatile section1 sbit T8P2REX         @ (unsigned) &T8P2OC * 8 + 6 ;
static volatile section1 sbit T8P2TRN         @ (unsigned) &T8P2OC * 8 + 7 ;

/*      T8P1PDT bits      */
static volatile section1 sbit T8P1PDT0        @ (unsigned) &T8P1PDT * 8 + 0 ;
static volatile section1 sbit T8P1PDT1        @ (unsigned) &T8P1PDT * 8 + 1 ;
static volatile section1 sbit T8P1PDT2        @ (unsigned) &T8P1PDT * 8 + 2 ;
static volatile section1 sbit T8P1PDT3        @ (unsigned) &T8P1PDT * 8 + 3 ;
static volatile section1 sbit T8P1PDT4        @ (unsigned) &T8P1PDT * 8 + 4 ;
static volatile section1 sbit T8P1PDT5        @ (unsigned) &T8P1PDT * 8 + 5 ;
static volatile section1 sbit T8P1PDT6        @ (unsigned) &T8P1PDT * 8 + 6 ;
static volatile section1 sbit T8P1PDT7        @ (unsigned) &T8P1PDT * 8 + 7 ;

/*      T8P2PDT bits      */
static volatile section1 sbit T8P2PDT0        @ (unsigned) &T8P2PDT * 8 + 0 ;
static volatile section1 sbit T8P2PDT1        @ (unsigned) &T8P2PDT * 8 + 1 ;
static volatile section1 sbit T8P2PDT2        @ (unsigned) &T8P2PDT * 8 + 2 ;
static volatile section1 sbit T8P2PDT3        @ (unsigned) &T8P2PDT * 8 + 3 ;
static volatile section1 sbit T8P2PDT4        @ (unsigned) &T8P2PDT * 8 + 4 ;
static volatile section1 sbit T8P2PDT5        @ (unsigned) &T8P2PDT * 8 + 5 ;
static volatile section1 sbit T8P2PDT6        @ (unsigned) &T8P2PDT * 8 + 6 ;
static volatile section1 sbit T8P2PDT7        @ (unsigned) &T8P2PDT * 8 + 7 ;

/*      T8P1PEX bits      */
static volatile section1 sbit T8P1POSEX0      @ (unsigned) &T8P1PEX * 8 + 0 ;
static volatile section1 sbit T8P1POSEX1      @ (unsigned) &T8P1PEX * 8 + 1 ;
static volatile section1 sbit T8P1POSEX2      @ (unsigned) &T8P1PEX * 8 + 2 ;
static volatile section1 sbit T8P1POSEX3      @ (unsigned) &T8P1PEX * 8 + 3 ;

/*      T8P2PEX bits      */
static volatile section1 sbit T8P2POSEX0      @ (unsigned) &T8P2PEX * 8 + 0 ;
static volatile section1 sbit T8P2POSEX1      @ (unsigned) &T8P2PEX * 8 + 1 ;
static volatile section1 sbit T8P2POSEX2      @ (unsigned) &T8P2PEX * 8 + 2 ;
static volatile section1 sbit T8P2POSEX3      @ (unsigned) &T8P2PEX * 8 + 3 ;

/*      ADCCL bits      */
static volatile section1 sbit ADEN            @ (unsigned) &ADCCL * 8 + 0 ;
static volatile section1 sbit ADTRG           @ (unsigned) &ADCCL * 8 + 1 ;
static volatile section1 sbit ADCHS0          @ (unsigned) &ADCCL * 8 + 2 ;
static volatile section1 sbit ADCHS1          @ (unsigned) &ADCCL * 8 + 3 ;
static volatile section1 sbit ADCHS2          @ (unsigned) &ADCCL * 8 + 4 ;
static volatile section1 sbit ADVREFS0        @ (unsigned) &ADCCL * 8 + 5 ;
static volatile section1 sbit ADVREFS1        @ (unsigned) &ADCCL * 8 + 6 ;
static volatile section1 sbit ADVREFS2        @ (unsigned) &ADCCL * 8 + 7 ;

/*      ADCCH bits      */
static volatile section1 sbit ADST0           @ (unsigned) &ADCCH * 8 + 0 ;
static volatile section1 sbit ADST1           @ (unsigned) &ADCCH * 8 + 1 ;
static volatile section1 sbit ADST2           @ (unsigned) &ADCCH * 8 + 2 ;
static volatile section1 sbit ADST3           @ (unsigned) &ADCCH * 8 + 3 ;
static volatile section1 sbit ADCS0           @ (unsigned) &ADCCH * 8 + 4 ;
static volatile section1 sbit ADCS1           @ (unsigned) &ADCCH * 8 + 5 ;
static volatile section1 sbit ADCS2           @ (unsigned) &ADCCH * 8 + 6 ;
static volatile section1 sbit ADFM            @ (unsigned) &ADCCH * 8 + 7 ;

/*      ADCTR bits      */
static volatile section1 sbit AD2VCALS        @ (unsigned) &ADCTR * 8 + 0 ;
static volatile section1 sbit TRIGEN          @ (unsigned) &ADCTR * 8 + 4 ;
static volatile section1 sbit TRIGPEG         @ (unsigned) &ADCTR * 8 + 5 ;
static volatile section1 sbit TRIGS           @ (unsigned) &ADCTR * 8 + 6 ;

/*      CALPROT bits      */
static volatile section1 sbit CALPROT0         @ (unsigned) &CALPROT * 8 + 0 ;

#endif

